#config_version=4
hardware:
  platform: p3_roc
  driverboards: pdb
mpf:
  auto_create_switch_events: true
  switch_event_active: '%active'
  switch_event_inactive: '%inactive'
#leds:
#  l_led0:
#    number: 0-0-2-3
#    brightness_compensation: 0.9
#    tags: playfield
#    fade_ms: 100
#    polarity: true
#  l_led1:
#    number: 0-1-4-5
#    brightness_compensation: 0.9
#    tags: playfield
#    polarity: true
#light_player:
#  mode_attract_started:
#    leds: l_led0, l_led1
#    script: flash
#    tocks_per_sec: 8
#    key: sw_moo
#    repeat: yes
#  sw_moo:
#    key: sw_moo
#    action: stop
#  pew_active:
#    leds: l_led0, l_led1
#    script: steady
#    speed: 8
#    loops: true
#  pew_inactive:
#    leds: l_led0, l_led1
#    script: off_mode
#    speed: 8
#    loops: true
#    key: sw_moo
#light_scripts:
#  flash:
#    - tocks: 1
#      color: ffffff
#    - tocks: 1
#      color: 0
#  steady:
#    - tocks: 1
#      color: ffffff
#  off_mode:
#    - tocks: 1
#      color: 000000
switches:
  s_left_button:
    number: 23
    label:
    tags: flip_sw_l
  s_right_button:
    number: 22
    label:
    tags: flip_sw_r
  s_left_slingshot:
    number: 21
    label:
    tags: slingshot_sw_l
  s_right_slingshot:
    number: 20
    label:
    tags: slingshot_sw_r
  s_start_button:
    number: 24
    label:
    tags: start_sw, start
  s_trough1:
    number: 25
  s_trough2:
    number: 26
#  s_trough3:
#    number: 27
#  s_trough4:
#    number: 28
  s_trough_jam:
    number: 29
  s_plunger_lane:
    number: 30
coils:
  c_flipperLeftMain:
    number: A0-B0-0
    pulse_ms: 20
    hold_power: 1
  c_flipperRightMain:
    number: A0-B0-1
    pulse_ms: 20
    hold_power: 1
  c_slingshotLeftMain:
    number: A0-B0-3
    pulse_ms: 20
    hold_power: 1
  c_slingshotRightMain:
    number: A0-B0-2
    pulse_ms: 20
    hold_power: 1
  c_popBumper1:
    number: A0-B0-4
    pulse_ms: 20
    hold_power: 1
  c_trough_eject:
    number: A0-B0-5
    pulse_ms: 20
flippers:
  leftflipper:
    main_coil: c_flipperLeftMain
    activation_switch: s_left_button
    enable_events: machine_reset_phase_3
  rightflipper:
    main_coil: c_flipperRightMain
    activation_switch: s_right_button
    enable_events: machine_reset_phase_3
autofire_coils:
  leftslingshot:
    coil: c_slingshotLeftMain
    switch: s_left_slingshot
    enable_events: machine_reset_phase_3
  rightslingshot:
    coil: c_slingshotRightMain
    switch: s_right_slingshot
    enable_events: machine_reset_phase_3
  #popbumper1:
  #  coil: c_popBumper1
    #switch: s_start_button
  #  enable_events: machine_reset_phase_3
  #ballTrough:
  #  coil: c_trough_eject
    #switch: s_start_button
  #  enable_events: machine_reset_phase_3
ball_devices:
  bd_trough:
    #ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough_jam
    ball_switches: s_trough1, s_trough2, s_trough_jam
    eject_coil: c_trough_eject
#    tags: trough, home, drain, ball_add_live
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    debug: yes
    entrance_count_delay: 1000ms
  bd_plunger:
    ball_switches: s_plunger_lane
    mechanical_eject: true
widget_styles:
  default:
    font_name: Quadrit
    font_size: 10
    adjust_top: 2
    adjust_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    adjust_top: 3
    adjust_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    adjust_top: 2
    adjust_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    adjust_top: 1
    adjust_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    adjust_top: 2
    adjust_bottom: 3
  tall title:
    font_name: big_noodle_titling
    font_size: 20
modes:
    - base
machine:
  balls_installed: 2
