#config_version=3
hardware:
  platform: p3_roc
  driverboards: pdb
mpf:
  auto_create_switch_events: True
  switch_event_active: "%active"
  switch_event_inactive: "%inactive"
leds:
  l_led0:
    number: 0-0-2-3
    brightness_compensation: 0.9
    tags: playfield
    fade_ms: 100
    polarity: true
  l_led1:
    number: 0-1-4-5
    brightness_compensation: 0.9
    tags: playfield
    polarity: true
light_player:
  mode_attract_started:
    leds: l_led0, l_led1
    script: flash
    tocks_per_sec: 8
    key: sw_moo
    repeat: yes
  sw_moo:
    key: sw_moo
    action: stop
#  sw_moo:
#    leds: l_led0, l_led1
#    script: steady
#    tocks_per_sec: 1
#    repeat: no
  pew_active:
    leds: l_led0, l_led1
    script: steady
    tocks_per_sec: 8
    repeat: yes
#    key: sw_moo
  pew_inactive:
    leds: l_led0, l_led1
    script: off_mode
    tocks_per_sec: 8
    repeat: yes
    key: sw_moo
light_scripts:
  flash:
    - tocks: 1
      color: ffffff
    - tocks: 1
      color: 0
  steady:
    - tocks: 1
      color: ffffff
  off_mode:
    - tocks: 1
      color: 000000
switches:
  pew:
    number: 23
    label:
    tags: moo
#    activation_events: Amoo_start
#    deactivation_events: Amoo_end
Coils:
  flipperLeftMain:
    number: A0-B0-0
    pulse_ms: 20
    hold_power: 2
Flippers:
  leftFlipper:
    main_coil: flipperLeftMain
    activation_switch: pew
