#config_version=3
light_player:
  mode_attract_started:
    - show: attract_light_show
      repeat: yes
      tocks_per_sec: 1
  mode_attract_stopped:
    - show: attract_light_show
      action: stop
